# Generated by Django 3.2.4 on 2021-06-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Designation', models.CharField(max_length=20, null=True)),
                ('Skills', models.CharField(max_length=500, null=True)),
                ('links', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
