# Generated by Django 3.2.4 on 2021-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetable',
            name='rating',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resumetable',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumetable',
            name='template',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
