# Generated by Django 3.2.4 on 2021-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210624_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetable',
            name='rating',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
