# Generated by Django 3.2.4 on 2021-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_resumetable_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetable',
            name='resumeurl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
