# Generated by Django 3.2.4 on 2021-06-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resumetable_resumeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetable',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
